name: Hello World

on:
  workflow_dispatch:   # enables the "Run workflow" button

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "👋 Hello from GitHub Actions!"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit: $GITHUB_SHA"